### ISSUE TITLE
charset problem in zip restore

### ISSUE THREAD

**Issue by envagyok** [ikus060/rdiffweb#55] opened 2015-06-10 07:05 UTC
Rdiif on utf-8 system (Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-53-generic x86_64). On the web view and single file download is correct, but zip and tar download problem with Hungarian accented characters.

![20150610_083718](https://cloud.githubusercontent.com/assets/12825494/8076527/75b2a36e-0f4d-11e5-87b7-7e2be409c345.png)

**Comment by ikus060** [comment] 2015-06-10 11:52
I manage to reproduce the problem with zip file. Reading various topic on this subject, ZIP file used ISO-8859-1 encoding. It should be relatively simple to fix.

For tar.gz, I didn't manage to reproduce the problem.

**Comment by ikus060** [comment] 2015-06-11 11:38
I've work around a fix to this problem. I've found a solution to use the right encoding in ZIP archive. Since it involve encoding, it's not perfect. Unknown unicode character are replace by '?'. See screenshot.

![screenshot from 2015-06-11 07 36 35](https://cloud.githubusercontent.com/assets/921251/8106137/c003a994-100c-11e5-9afe-6bed02c50a04.png)

Soon, I will release a fix in master and develop branch.

**Comment by envagyok** [comment] 2015-06-11 11:53
Ok, thanks your job.

**Comment by ikus060** [comment] 2015-07-31 18:33
I've fixed the problem in develop branch. It won't be fixed in master branch (v0.7.0).

**Closed by ikus060** 2015-07-31 18:33 UTC
